name: janus-signalling-proxy-agent
base: core18
version: '0.0.1'
summary: Janus WebRTC Server websockets signalling proxy agent
description: |
  Helper application to use in combination with janus-signalling-proxy. Run on Janus instance side.
license: GPL-3.0+
grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: armhf

parts:
  lws:
    plugin: cmake
    source-type: git
    source: https://github.com/warmcat/libwebsockets.git
    source-branch: v3.1-stable
    configflags:
      - -DLWS_WITHOUT_TESTAPPS=ON
    build-packages:
      - libssl-dev
    stage-packages:
      - libssl1.1
  main:
    plugin: cmake
    source-type: git
    source: https://github.com/RSATom/janus-signalling-proxy.git
    after:
        - lws
    configflags:
      - -DBUILD_PROXY=OFF
    build-packages:
      - g++
      - make
      - pkg-config
      - libglib2.0-dev
      - libconfig-dev
      - libjansson-dev
    stage-packages:
      - libconfig9
      - libjansson4

apps:
  agent:
    command: AgentApp
    daemon: simple
    plugs:
      - network
      
